Add Scoreboard components
Ladysnake/Cardinal-Components-API pull request #36
Opened 2020-07-16 23:28 UTC by Pyrofab

This PR implements scoreboard and team components.
- Scoreboard components are attached to Scoreboard instances (accessible from any World) - they are essentially alternatives to level components. They may replace level components at some point, as they are less reliant on a fragile class hierarchy.
- Team components are attached to Team instances - they can be used to implement shared data between entities in the same team.

Both component providers support synchronized components. They get attached using the [experimental static component system](https://github.com/OnyxStudios/Cardinal-Components-API/wiki/Registering-and-using-a-component#static-registration)

Closes #34

2020-07-16 23:29 UTC, Pyrofab commented
@haykam821 opinions ?

2020-07-17 04:14 UTC, UpcraftLP commented on cardinal-components-scoreboard/src/main/java/dev/onyxstudios/cca/mixin/scoreboard/MixinScoreboardState.java
> +        if (this.scoreboard != null) {  // weird deferred loading thing
![tiny_potato](https://cdn.discordapp.com/attachments/552976908070027270/552978960896753665/2015-04-26_11.13.01.png)
[:star:](# ":iapprove:")

2020-07-17 04:18 UTC, UpcraftLP requested changes

2020-07-17 04:18 UTC, UpcraftLP commented on cardinal-components-scoreboard/src/main/resources/mixins.cardinal_components_scoreboard.json
> +  "minVersion": "0.7.11",
should probably be 0.8

2020-07-17 04:18 UTC, UpcraftLP commented on gradle.properties
> +mod_version = 2.4.2
not 2.5?

2020-07-22 08:22 UTC, UpcraftLP approved these changes

2020-07-22 14:28 UTC, merged